my: localhost:7080
zero: localhost:5080
port_offset: 0
postings: _data/p
wal: _data/w
tmp: _data/tmp

cache:
  size-mb: 1024
  percentage: 10,65,25

graphql:
  # Use to fetch schema during generation.
  introspection: true
  debug: false
  extensions: false
  poll-interval: 10s

limit:
  mutations: strict
  query-timeout: 1m

lambda:
  num: 0


telemetry:
  sentry: false
  reports: false

