{ or: [
    # Authorize root
    { rule: "{ $USERTYPE: {eq: \"Root\"} }" },
    # Authorize Owner
    { rule: """query ($OWNIDS: [String]) {
        queryRoleExt {
          nodes(filter: {rootnameid: {in: $OWNIDS}}) { id }
        }
    }""" },
    # Authorize user that have authority in nodes
    { rule: """query ($USERNAME: String!) {
        queryRoleExt {
          nodes {
            children(filter: {role_type: {in: [Coordinator]}}) {
              first_link(filter: {username: {eq: $USERNAME}}) { username }
            }
          }
        }
    }""" },
    { and: [ # Coordo in parent if no coordo in children level 0
      # -- Coordo in parent
      { rule: """query ($USERNAME: String!) {
          queryRoleExt {
            nodes {
              parent {
                children(filter: {role_type: {in: [Coordinator]}}) {
                  first_link(filter: {username: {eq: $USERNAME}}) { username }
                }
              }
            }
          }
      }""" },
      # -- No coordo in level 0
      { not: { rule: """query {
          queryRoleExt {
            nodes {
              children(filter: {role_type: {in: [Coordinator, Owner]}}) {
                first_link { username }
              }
            }
          }
      }""" }}
    ]}
  ]
}
