{ or: [
    # Authorize root
    { rule: "{ $USERTYPE: {eq: \"Root\"} }" },
    # Authorize public data
    { rule: """query {
        queryRoleExt {
          nodes(filter: {visibility: {eq: Public}}) { id }
        }
    }""" },
    # Authorize members
    { rule: """query ($ROOTIDS: [String]) {
        queryRoleExt(filter: {rootnameid: {in: $ROOTIDS}}) { id }
    }""" }
  ]
}
