{ or: [
    # Authorize root
    { rule: "{ $USERTYPE: {eq: \"Root\"} }" },
    # Authorize public data
    { rule: """query {
        queryTensionTemplate {
          nodes(filter: {visibility: {eq: Public}}) { id }
        }
    }""" },
    # Authorize private data (members only)
    { rule: """query ($ROOTIDS: [String]) {
        queryTensionTemplate(filter: {rootnameid: {in: $ROOTIDS}}) {
          nodes(filter: {visibility: {eq: Private}}) { id }
        }
    }""" },
    # Authorize secret data (explicit member only)
    # -- parent
    { rule: """query ($USERNAME: String!) {
        queryTensionTemplate {
          nodes(filter: {visibility: {eq: Secret}}) {
            children {
              first_link(filter: {username: {eq: $USERNAME}}) { username }
            }
          }
        }
    }""" },
    # -- children (including secret circle!)
    { rule: """query ($USERNAME: String!) {
        queryTensionTemplate {
          nodes(filter: {visibility: {eq: Secret}}) {
            parent {
              children {
                first_link(filter: {username: {eq: $USERNAME}}) { username }
              }
            }
          }
        }
    }""" }
  ]
}
