{ or: [
    # Authorize root
    { rule: "{ $USERTYPE: {eq: \"Root\"} }" },
    # Authorize author
    { rule: """query ($USERNAME: String!) {
      queryContract {
        createdBy(filter: {username: {eq: $USERNAME}}) { username }
      }
    }""" },
    # Authorize candidates
    { rule: """query ($USERNAME: String!) {
      queryContract {
        candidates(filter: {username: {eq: $USERNAME}}) { username }
      }
    }""" },
    # Authorize public data OR Owner
    { rule: """query ($OWNIDS: [String]) {
        queryContract {
          tension { receiver(filter: {visibility: {eq: Public}, or: [{rootnameid: {in: $OWNIDS}}]}) { id } }
        }
    }""" },
    # Authorize private data (members only)
    { rule: """query ($ROOTIDS: [String]) {
        queryContract {
          tension { receiver(filter: {visibility: {eq: Private}, and: [{rootnameid: {in: $ROOTIDS}}]}) { id } }
        }
    }""" },
    # Authorize secret data (explicit member only)
    { rule: """query ($USERNAME: String!) {
        queryContract {
          tension {
            receiver(filter: {visibility: {eq: Secret}}) {
              children {
                first_link(filter: {username: {eq: $USERNAME}}) { username }
              }
            }
          }
        }
    }""" }
  ]
}
